package graphql

import (
	"context"
	"net/http"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/f2u0a0d3/GoRecon/pkg/config"
	"github.com/f2u0a0d3/GoRecon/pkg/core"
	"github.com/f2u0a0d3/GoRecon/pkg/intelligence"
	"github.com/rs/zerolog/log"
)

type Server struct {
	config     *config.Config
	manager    *core.PluginManager
	correlator *intelligence.IntelligenceCorrelator
	httpServer *http.Server
}

type Resolver struct {
	manager    *core.PluginManager
	correlator *intelligence.IntelligenceCorrelator
}

func NewServer(cfg *config.Config, manager *core.PluginManager, correlator *intelligence.IntelligenceCorrelator) *Server {
	return &Server{
		config:     cfg,
		manager:    manager,
		correlator: correlator,
	}
}

func (s *Server) Start(ctx context.Context) error {
	resolver := &Resolver{
		manager:    s.manager,
		correlator: s.correlator,
	}

	mux := http.NewServeMux()
	
	// GraphQL endpoint
	srv := handler.NewDefaultServer(NewExecutableSchema(Config{Resolvers: resolver}))
	mux.Handle("/graphql", srv)
	
	// GraphQL playground for development
	mux.Handle("/playground", playground.Handler("GraphQL playground", "/graphql"))

	port := ":8081" // Default GraphQL port
	if s.config.API.GraphQL.Port != "" {
		port = ":" + s.config.API.GraphQL.Port
	}

	s.httpServer = &http.Server{
		Addr:    port,
		Handler: mux,
	}

	log.Info().
		Str("port", port).
		Msg("Starting GraphQL server")

	go func() {
		<-ctx.Done()
		s.Stop()
	}()

	if err := s.httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
		return err
	}

	return nil
}

func (s *Server) Stop() error {
	log.Info().Msg("Shutting down GraphQL server")
	
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	
	return s.httpServer.Shutdown(ctx)
}

// Mock schema and types for demonstration
type Config struct {
	Resolvers interface{}
}

func NewExecutableSchema(cfg Config) *handler.Server {
	// This would normally be generated by gqlgen
	// For now, returning a mock server
	return handler.NewDefaultServer(nil)
}